# Generated by Django 5.1 on 2024-08-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="senha",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
