# Generated by Django 5.1 on 2024-08-28 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10)),
                ("nome", models.CharField(max_length=10)),
                ("periodicidade", models.DurationField()),
                ("valor_de_compra", models.FloatField()),
                ("valor_de_venda", models.FloatField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ativos",
                        to="Usuario.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preco", models.FloatField()),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "ativo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="Ativo.ativo",
                    ),
                ),
            ],
        ),
    ]
