# Generated by Django 5.1 on 2024-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ativo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ativo",
            name="periodicidade",
            field=models.CharField(max_length=10),
        ),
    ]
