# Generated by Django 5.1 on 2024-08-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ativo", "0004_remove_ativo_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historico",
            name="data_hora",
            field=models.DateTimeField(),
        ),
    ]
